In [1]:
import sys, os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="6,7"
import torch
import torch.nn as nn

In [2]:
# N is batch size; D_in is input dimension;
N, D_in = 256, 57
x = torch .randn(N, D_in, D_in)

In [3]:
x.shape

torch.Size([4, 57, 57])

In [4]:
x

tensor([[[-0.5698, -1.1161, -0.1430,  ...,  0.4380,  0.8362, -1.6317],
         [-0.4147, -1.2465, -0.9486,  ..., -1.8635,  0.2055, -0.0196],
         [ 0.1592,  0.2652,  0.1499,  ...,  1.9248,  0.7659,  1.1522],
         ...,
         [-2.8059,  0.1896, -0.8612,  ...,  0.4869,  0.2740,  0.8898],
         [-0.9809, -0.9729,  0.6318,  ...,  0.1929,  0.8506,  1.2578],
         [-0.2670, -0.2413, -1.1424,  ...,  0.0991, -1.1094,  1.0201]],

        [[-0.6461,  0.3777,  1.4531,  ...,  1.1083,  0.1665,  0.1273],
         [-0.2944, -2.4850,  0.5173,  ...,  0.5249,  1.5764,  1.3663],
         [ 0.6994, -1.1045, -0.5965,  ..., -1.3746, -0.0460, -0.0278],
         ...,
         [-0.2940,  0.8063, -0.3636,  ...,  0.2478, -0.4572, -0.4809],
         [-0.2917,  1.7565,  0.6858,  ...,  0.7214,  0.0804,  0.1214],
         [-0.3046,  0.1756,  1.3562,  ...,  0.5297,  1.8142,  0.1591]],

        [[ 0.1930, -0.1345,  1.8636,  ...,  0.3847,  2.3211, -1.2157],
         [ 0.1935,  0.2588, -1.9458,  ...,  2

In [5]:
import sys  
sys.path.insert(0, './viplab_projects/satellite-knowledge-distillation')
from models.unet_optimize import UNet


In [6]:
maxpool = nn.MaxPool2d(2)
y = maxpool(x)

In [7]:
y.shape

torch.Size([4, 28, 28])

In [8]:
y

tensor([[[-0.4147,  0.4514,  0.5610,  ...,  0.3806,  2.1896,  0.8362],
         [ 0.4475,  0.6715,  0.4791,  ..., -0.5094,  0.5328,  1.9248],
         [ 2.0162,  1.0966,  1.0360,  ...,  0.5698,  0.0714,  1.2281],
         ...,
         [ 0.9504,  0.5219,  1.6624,  ...,  0.7104,  2.0454,  1.1255],
         [ 0.4251,  2.4307,  1.7459,  ...,  2.3768,  1.9729,  2.6182],
         [ 0.1896,  1.6338,  0.7815,  ...,  0.6797,  0.4107,  0.8506]],

        [[ 0.3777,  1.4531, -0.0795,  ..., -0.2437,  1.3003,  1.5764],
         [ 1.3034,  1.2437,  0.7075,  ...,  1.5430,  1.8150,  1.2577],
         [ 0.0756,  1.6608,  0.5250,  ...,  2.1470,  1.0505,  0.2065],
         ...,
         [ 0.8413,  2.5230,  0.8502,  ...,  0.3530, -0.1141,  1.9346],
         [ 0.7762,  1.1328, -0.1004,  ...,  0.7284, -0.1562,  0.3340],
         [ 1.7565,  1.4965,  1.2988,  ...,  0.3364,  2.1169,  0.7214]],

        [[ 0.2588,  1.8636,  2.3385,  ...,  0.6374,  0.7342,  2.3211],
         [ 1.0820,  2.9263,  0.5745,  ...,  0

In [9]:
# N is batch size; D_in is input dimension;
# x: (B, num_channels, H, W) input tensor
B, num_channels, D_in = 8, 512, 32
x = torch.randn(B, num_channels , D_in, D_in)
B, num_channels, D_in = 8, 256, 64
conv3 = torch.randn(B, num_channels , D_in, D_in)

In [10]:
x.shape

torch.Size([8, 512, 32, 32])

In [11]:
dconv_down_3 = nn.Conv2d(512, 512, 3, padding=1)
x = dconv_down_3(x)

In [12]:
x.shape

torch.Size([8, 512, 32, 32])

In [13]:
y = nn.functional.interpolate(x, scale_factor=2, mode='bilinear', align_corners=True)

In [14]:
y.shape

torch.Size([8, 512, 64, 64])

In [15]:
y = torch.cat([y, conv3], dim=1)

In [16]:
y.shape

torch.Size([8, 768, 64, 64])

In [35]:
B, N, D_in = 2, 4, 3
x = torch .randn(B, N, D_in, D_in)

In [36]:
x.shape

torch.Size([2, 4, 3, 3])

In [37]:
x

tensor([[[[-1.8559,  1.7953,  0.7394],
          [ 0.4701,  0.8579,  0.1233],
          [-1.4959,  0.7552,  3.3919]],

         [[ 2.0854, -0.9397, -0.0161],
          [ 2.1468,  0.7873,  0.8755],
          [ 0.0436,  1.7201, -1.4889]],

         [[-1.0629, -1.4418,  0.0036],
          [ 0.3247,  1.0564,  0.4423],
          [-1.0490,  0.1896,  0.4612]],

         [[ 3.4334, -1.4929, -0.4212],
          [ 0.1965, -1.0018, -1.3456],
          [ 0.1704, -1.4278,  0.0092]]],


        [[[-0.6010,  0.1292,  0.8632],
          [-1.4959,  0.3281, -0.5692],
          [ 0.0821,  1.5549,  0.4750]],

         [[-0.3031,  0.6711, -0.2277],
          [-1.4501, -1.0465,  0.2629],
          [ 1.1517, -0.6513, -1.2706]],

         [[-1.4647,  0.0531,  0.8869],
          [-0.0889, -0.2390, -0.5726],
          [-1.4972,  0.5497, -2.0435]],

         [[-0.7776, -0.1172, -1.2740],
          [ 1.3024,  0.8208, -1.3431],
          [ 0.1948,  1.5683, -1.5604]]]])

In [71]:
x_rgb = x[:,0:3,:,:]
x_rgb.shape

torch.Size([2, 3, 3, 3])

In [72]:
x_rgb

tensor([[[[-1.8559,  1.7953,  0.7394],
          [ 0.4701,  0.8579,  0.1233],
          [-1.4959,  0.7552,  3.3919]],

         [[ 2.0854, -0.9397, -0.0161],
          [ 2.1468,  0.7873,  0.8755],
          [ 0.0436,  1.7201, -1.4889]],

         [[-1.0629, -1.4418,  0.0036],
          [ 0.3247,  1.0564,  0.4423],
          [-1.0490,  0.1896,  0.4612]]],


        [[[-0.6010,  0.1292,  0.8632],
          [-1.4959,  0.3281, -0.5692],
          [ 0.0821,  1.5549,  0.4750]],

         [[-0.3031,  0.6711, -0.2277],
          [-1.4501, -1.0465,  0.2629],
          [ 1.1517, -0.6513, -1.2706]],

         [[-1.4647,  0.0531,  0.8869],
          [-0.0889, -0.2390, -0.5726],
          [-1.4972,  0.5497, -2.0435]]]])

In [75]:
x_Nir = x[:,3,:,:]
x_Nir.shape

torch.Size([2, 3, 3])

In [76]:
x_Nir

tensor([[[ 3.4334, -1.4929, -0.4212],
         [ 0.1965, -1.0018, -1.3456],
         [ 0.1704, -1.4278,  0.0092]],

        [[-0.7776, -0.1172, -1.2740],
         [ 1.3024,  0.8208, -1.3431],
         [ 0.1948,  1.5683, -1.5604]]])